// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application;

public partial class AspNetUsers
{
    public string Id { get; set; }

    public string UserName { get; set; }

    public string NormalizedUserName { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<PlanningRoom> PlanningRoom { get; set; } = new List<PlanningRoom>();

    public virtual ICollection<PlanningRoomUsers> PlanningRoomUsers { get; set; } = new List<PlanningRoomUsers>();

    public virtual ICollection<ProductBacklogItemEstimate> ProductBacklogItemEstimate { get; set; } = new List<ProductBacklogItemEstimate>();
}