// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application;

public partial class EstimateValue
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public int Order { get; set; }

    public string Label { get; set; }

    public int Value { get; set; }

    public virtual EstimateValueCategory Category { get; set; }

    public virtual ICollection<ProductBacklogItemEstimate> ProductBacklogItemEstimate { get; set; } = new List<ProductBacklogItemEstimate>();
}