// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application;

public partial class PlanningRoom
{
    public int Id { get; set; }

    public string Description { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreationUserId { get; set; }

    public int EstimateValueCategoryId { get; set; }

    public virtual AspNetUsers CreationUser { get; set; }

    public virtual EstimateValueCategory EstimateValueCategory { get; set; }

    public virtual ICollection<PlanningRoomUsers> PlanningRoomUsers { get; set; } = new List<PlanningRoomUsers>();

    public virtual ICollection<ProductBacklogItem> ProductBacklogItem { get; set; } = new List<ProductBacklogItem>();
}