// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application;

public partial class ProductBacklogItemEstimate
{
    public int Id { get; set; }

    public int ProductBacklogItemId { get; set; }

    public string UserId { get; set; }

    public int EstimateValueId { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual EstimateValue EstimateValue { get; set; }

    public virtual ProductBacklogItem ProductBacklogItem { get; set; }

    public virtual AspNetUsers User { get; set; }
}