// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application;

public partial class ProductBacklogItemStatus
{
    public int Id { get; set; }

    public string Label { get; set; }

    public int Order { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<ProductBacklogItem> ProductBacklogItem { get; set; } = new List<ProductBacklogItem>();
}