// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PlanningPoker.Application;
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application.Configurations
{
    public partial class EstimateValueConfiguration : IEntityTypeConfiguration<EstimateValue>
    {
        public void Configure(EntityTypeBuilder<EstimateValue> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07E7E2A322");

            entity.Property(e => e.Label)
            .IsRequired()
            .HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.EstimateValue)
            .HasForeignKey(d => d.CategoryId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_EstimateValue_ToTable");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EstimateValue> entity);
    }
}
