// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PlanningPoker.Application;
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application.Configurations
{
    public partial class PlanningRoomConfiguration : IEntityTypeConfiguration<PlanningRoom>
    {
        public void Configure(EntityTypeBuilder<PlanningRoom> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07AC9288F0");

            entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.CreationUserId)
            .IsRequired()
            .HasMaxLength(450);
            entity.Property(e => e.Description)
            .IsRequired()
            .HasMaxLength(50);

            entity.HasOne(d => d.CreationUser).WithMany(p => p.PlanningRoom)
            .HasForeignKey(d => d.CreationUserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PlanningRoom_ToTable");

            entity.HasOne(d => d.EstimateValueCategory).WithMany(p => p.PlanningRoom)
            .HasForeignKey(d => d.EstimateValueCategoryId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PlanningRoom_ToTable_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlanningRoom> entity);
    }
}
