// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PlanningPoker.Application;
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application.Configurations
{
    public partial class PlanningRoomUsersConfiguration : IEntityTypeConfiguration<PlanningRoomUsers>
    {
        public void Configure(EntityTypeBuilder<PlanningRoomUsers> entity)
        {
            entity.HasKey(e => new { e.UserId, e.PlanningRoomId }).HasName("PK__Planning__79102391E89C42C3");

            entity.HasOne(d => d.PlanningRoom).WithMany(p => p.PlanningRoomUsers)
            .HasForeignKey(d => d.PlanningRoomId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PlanningRoomUsers_ToTable");

            entity.HasOne(d => d.User).WithMany(p => p.PlanningRoomUsers)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PlanningRoomUsers_ToTable_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlanningRoomUsers> entity);
    }
}
