// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PlanningPoker.Application;
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application.Configurations
{
    public partial class ProductBacklogItemConfiguration : IEntityTypeConfiguration<ProductBacklogItem>
    {
        public void Configure(EntityTypeBuilder<ProductBacklogItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductB__3214EC075FA54AE4");

            entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.Description)
            .IsRequired()
            .HasMaxLength(250);

            entity.HasOne(d => d.PlanningRoom).WithMany(p => p.ProductBacklogItem)
            .HasForeignKey(d => d.PlanningRoomId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ProductBacklogItem_ToTable_1");

            entity.HasOne(d => d.Status).WithMany(p => p.ProductBacklogItem)
            .HasForeignKey(d => d.StatusId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ProductBacklogItem_ToTable");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductBacklogItem> entity);
    }
}
