// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PlanningPoker.Application;
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application.Configurations
{
    public partial class ProductBacklogItemStatusConfiguration : IEntityTypeConfiguration<ProductBacklogItemStatus>
    {
        public void Configure(EntityTypeBuilder<ProductBacklogItemStatus> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductB__3214EC07354F0823");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))")
            .HasColumnName("Is_Active");
            entity.Property(e => e.Label)
            .IsRequired()
            .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductBacklogItemStatus> entity);
    }
}
