// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PlanningPoker.Application;
using System;
using System.Collections.Generic;

namespace PlanningPoker.Application.Configurations
{
    public partial class ProductBacklogItemEstimateConfiguration : IEntityTypeConfiguration<ProductBacklogItemEstimate>
    {
        public void Configure(EntityTypeBuilder<ProductBacklogItemEstimate> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductB__3214EC07F2367097");

            entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.UserId)
            .IsRequired()
            .HasMaxLength(450);

            entity.HasOne(d => d.EstimateValue).WithMany(p => p.ProductBacklogItemEstimate)
            .HasForeignKey(d => d.EstimateValueId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Table_ToTable_2");

            entity.HasOne(d => d.ProductBacklogItem).WithMany(p => p.ProductBacklogItemEstimate)
            .HasForeignKey(d => d.ProductBacklogItemId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Table_ToTable");

            entity.HasOne(d => d.User).WithMany(p => p.ProductBacklogItemEstimate)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Table_ToTable_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductBacklogItemEstimate> entity);
    }
}
