// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Domain;

public partial class PlanningRoomUsers
{
    public int PlanningRoomId { get; set; }

    public string UserId { get; set; }

    public virtual PlanningRoom PlanningRoom { get; set; }

    public virtual AspNetUsers User { get; set; }
}