// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanningPoker.Domain;

public partial class ProductBacklogItem
{
    public int Id { get; set; }

    public int PlanningRoomId { get; set; }

    public string Description { get; set; }

    public DateTime CreateDate { get; set; }

    public int StatusId { get; set; }

    public virtual PlanningRoom PlanningRoom { get; set; }

    public virtual ICollection<ProductBacklogItemEstimate> ProductBacklogItemEstimate { get; set; } = new List<ProductBacklogItemEstimate>();

    public virtual ProductBacklogItemStatus Status { get; set; }
}